// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QMSofts.Identity.Data;

#nullable disable

namespace QMSofts.Identity.Migrations;

[DbContext(typeof(IdentityDbContext))]
partial class IdentityDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasDefaultSchema("identity")
            .HasAnnotation("ProductVersion", "8.0.8")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("QMSofts.Identity.Models.AppEntitlement", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<string>("AppKey").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)");
            b.Property<DateTimeOffset>("GrantedAt").HasColumnType("timestamp with time zone");
            b.Property<Guid>("UserId").HasColumnType("uuid");
            b.HasKey("Id");
            b.HasIndex("UserId", "AppKey").IsUnique();
            b.ToTable("AppEntitlements", "identity");
        });

        modelBuilder.Entity("QMSofts.Identity.Models.AuthAuditRecord", b =>
        {
            b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));
            b.Property<string>("AppKey").HasMaxLength(50).HasColumnType("character varying(50)");
            b.Property<string>("Detail").HasMaxLength(1000).HasColumnType("character varying(1000)");
            b.Property<int>("EventType").HasColumnType("integer");
            b.Property<string>("Identifier").HasMaxLength(256).HasColumnType("character varying(256)");
            b.Property<string>("IpAddress").HasMaxLength(64).HasColumnType("character varying(64)");
            b.Property<DateTimeOffset>("OccurredAt").HasColumnType("timestamp with time zone");
            b.Property<Guid?>("UserId").HasColumnType("uuid");
            b.Property<string>("UserAgent").HasMaxLength(512).HasColumnType("character varying(512)");
            b.HasKey("Id");
            b.HasIndex("EventType");
            b.HasIndex("OccurredAt");
            b.HasIndex("UserId");
            b.ToTable("AuthAuditRecords", "identity");
        });

        modelBuilder.Entity("QMSofts.Identity.Models.RefreshToken", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<DateTimeOffset>("ExpiresAt").HasColumnType("timestamp with time zone");
            b.Property<DateTimeOffset?>("RevokedAt").HasColumnType("timestamp with time zone");
            b.Property<string>("TokenHash").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
            b.Property<Guid>("UserId").HasColumnType("uuid");
            b.HasKey("Id");
            b.HasIndex("TokenHash");
            b.HasIndex("UserId");
            b.ToTable("RefreshTokens", "identity");
        });

        modelBuilder.Entity("QMSofts.Identity.Models.Role", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<string>("Description").HasMaxLength(300).HasColumnType("character varying(300)");
            b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
            b.HasKey("Id");
            b.HasIndex("Name").IsUnique();
            b.ToTable("Roles", "identity");
        });

        modelBuilder.Entity("QMSofts.Identity.Models.User", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<string>("Email").IsRequired().HasMaxLength(256).HasColumnType("character varying(256)");
            b.Property<int>("FailedLoginCount").HasColumnType("integer");
            b.Property<bool>("IsActive").HasColumnType("boolean");
            b.Property<DateTimeOffset?>("LockedUntil").HasColumnType("timestamp with time zone");
            b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
            b.Property<string>("NormalizedEmail").IsRequired().HasMaxLength(256).HasColumnType("character varying(256)");
            b.Property<string>("PasswordHash").IsRequired().HasColumnType("text");
            b.Property<int>("TokenVersion").HasColumnType("integer");
            b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamp with time zone");
            b.HasKey("Id");
            b.HasIndex("NormalizedEmail").IsUnique();
            b.ToTable("Users", "identity");
        });

        modelBuilder.Entity("QMSofts.Identity.Models.UserRole", b =>
        {
            b.Property<Guid>("UserId").HasColumnType("uuid");
            b.Property<Guid>("RoleId").HasColumnType("uuid");
            b.HasKey("UserId", "RoleId");
            b.HasIndex("RoleId");
            b.ToTable("UserRoles", "identity");
        });

        modelBuilder.Entity("QMSofts.Identity.Models.AppEntitlement", b =>
        {
            b.HasOne("QMSofts.Identity.Models.User", "User")
                .WithMany("AppEntitlements").HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade).IsRequired();
            b.Navigation("User");
        });

        modelBuilder.Entity("QMSofts.Identity.Models.RefreshToken", b =>
        {
            b.HasOne("QMSofts.Identity.Models.User", "User")
                .WithMany("RefreshTokens").HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade).IsRequired();
            b.Navigation("User");
        });

        modelBuilder.Entity("QMSofts.Identity.Models.UserRole", b =>
        {
            b.HasOne("QMSofts.Identity.Models.Role", "Role")
                .WithMany("UserRoles").HasForeignKey("RoleId")
                .OnDelete(DeleteBehavior.Cascade).IsRequired();
            b.HasOne("QMSofts.Identity.Models.User", "User")
                .WithMany("UserRoles").HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade).IsRequired();
            b.Navigation("Role");
            b.Navigation("User");
        });

        modelBuilder.Entity("QMSofts.Identity.Models.Role", b => b.Navigation("UserRoles"));

        modelBuilder.Entity("QMSofts.Identity.Models.User", b =>
        {
            b.Navigation("AppEntitlements");
            b.Navigation("RefreshTokens");
            b.Navigation("UserRoles");
        });
    }
}
